apiVersion: v1
kind: Service
metadata:
  name: webapp02-service
spec:
  type: LoadBalancer
  selector:
    app: webapp02
  ports:
  - protocol: TCP
    port: 3000        # external port
    targetPort: 80    # container port
